### PR TITLE
[WIP] Generates separated xsd file providing php:PhpClassName for better type hints

### PR DESCRIPTION
**Pull request by Alphatone**
At the FLUIDTYPO3 Workshop in Denmark @DanielSiepmann was kind enough to implement some changes with me. As a non php developer I tried to finish up our work and would be happy if someone else can take it from here, or at least help me getting this change done.

**What it does:**
We generate two separate xsd files one being schema.xsd, one being phpNamespace.xsd. The second one gets imported in schema.xsd and provides a namespace prefix (currently "php:"). We check for arguments of type object (e.g. ArrayAccess) in viewhelpers and generate a type definition in phpNamespace.xsd that allows us to use the parameter `type="php:ArrayAccess"` in schema.xsd.

That way we get rid of the "anySimpleType" type in documentation and therefore can provide more precise information.

**What it still needs :**
We still need to test and implement a solution for viewhelpers accepting multiple different objects

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
I'll try to check the generation in conjunction with ViewHelper Reference generation in the upcoming weeks.

**Comment by lolli42** [comment]
Hey.

I'm aiming to integrate the schema generator into fluid directly, that's the reason I'm currently looking at open PR's and issues.
I don't understand everything of this PR and don't feel as if I could finish it within a reasonable amount of time.
I hope it's ok to close here for now since this PR stalled for 3 years already.
In case anyone picks up again, we should resurrect within Fluid directly later.

**Comment by Alphatone** [comment]
Thx for the notice :) If I recall correctly the PR was about enabling better autocompletion / expected values of type of objects and arrays.

**Comment by lolli42** [comment]
Thanks for feedback.

I understand the general idea of this, but not its detail implementation.
I think the main generator is great as such, my main goal is to package this into Fluid directly and keep maintaining it there.
As such, my goal is to solve issues & PR's here that are not ready to go *now*, and to pick up what is needed within Fluid later, in case things are picked up again.
Having this repo integrated within Fluid simplifies usage for developers. This should give this functionality a better general visibility and we can see what should be done to improve it.

**Pull request closed without merging**
